### ISSUE TITLE
[docs] Firebase Login API 명세서

### ISSUE THREAD

**Issue by crossbell8368** [1OS-DevTeam/TeamPlan#2]
## Description ( todo 설명 )

SNS로그인 서비스에 활용되는 Firebase API 분석 & 명세서 작성

## Task ( todo )

- [x] FireAuth api 확인
- [x] Firebase SNS Login 관련 API 확인
- [ ] API 명세서 작성

## References

[Firebase](https://firebase.google.com)

**Comment by crossbell8368** [comment]
기능별 API 명세서 구성 후 별도 Issue로 오픈
