### ISSUE TITLE
[feat] firebase package 배포방식

### ISSUE THREAD

**Issue by crossbell8368** [1OS-DevTeam/TeamPlan#8]
## Description ( todo 설명 )

* Firebase Package 공유방식 설정
* .gitignore에 추가된 swiftpackagemanager를 제거하기에는, 이후 dependency 및 경로 이슈가 발생할수도 있음
* 작성된 package.swift 파일공유 시, 빌드단계에서 문제확인
* 손쉽고, merge conflict 및 빌드오류가 발생하지 않는 firebase package 공유방식 확인

## Task ( todo )

- [x] Package.swift 공유방식 test
- [x] 패키지 버젼 및 SPM에 추가되는 URL 및 패키지 공유방식 테스트
- [x] 접근성이 뛰어나고 오류가 적은 방식으로 공유

**Comment by crossbell8368** [comment]
## Firebase 패키지 공유방식

* Local 환경에서 SPM을 통해 지정 package 버젼을 받아서 사용

### 1. 다운로드 URL로 package 추가
* https://github.com/firebase/firebase-ios-sdk.git
* Dependency Rule 은 Exact Version으로 & 9.5.0 으로 설정
![스크린샷 2023-02-18 오후 8 15 00](https://user-images.githubusercontent.com/50852143/219857425-f24fe476-f0af-41df-b590-f55b2d9249b3.png)

### 2. FirebaseAuth & Firestore 패키지 선택
![스크린샷 2023-02-18 오후 8 15 56](https://user-images.githubusercontent.com/50852143/219857477-ededfe7f-0577-4c95-bac1-b6c4f1230b5e.png)

### 3. 설정된 프로젝트 package dependencies
![스크린샷 2023-02-18 오후 8 16 17](https://user-images.githubusercontent.com/50852143/219857520-cac49758-0cbc-4e8b-9284-15fa66fb212d.png)

**Comment by crossbell8368** [comment]
## 20230227 : 변경사항

* Tuist의 도입으로 project.swift 파일에 SPM을 직접 기입하여 배포예정
